server:
  port: 8001
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: E://project/spring-boot-demo/cloud-config   # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码